/**
 * Seed generator. Reads sources.json and emits SQL to stdout that:
 *   - Removes any previously-seeded ep-gutenberg-* / ep-elementor-* pages
 *     (or only the targeted source/editor when filters are passed).
 *   - Inserts one page per (source × editor) with EmbedPress markup ready to render.
 *
 * Usage (typically via `bash scripts/seed-pages.sh`):
 *   tsx seed/index.ts                          # all sources × {gutenberg, elementor}
 *   tsx seed/index.ts --source YouTube         # one source, both editors
 *   tsx seed/index.ts --editor gutenberg       # all sources, Gutenberg only
 *   tsx seed/index.ts --source YouTube --editor elementor
 *
 * The output is meant to be piped into MySQL inside the docker container:
 *   tsx seed/index.ts | docker exec -i ep_e2e_db mysql -uwpuser -pwppass wordpress
 */
import { Editor, Source, getSources, pageSlug, pageTitle } from './sources';
import { buildGutenbergContent } from './editors/gutenberg';
import { buildElementorData } from './editors/elementor';

const SEED_ID_START = 1000;
const ELEMENTOR_VERSION = '3.18.0';

interface CliArgs {
  source?: string;
  editor?: Editor;
}

function parseArgs(argv: string[]): CliArgs {
  const args: CliArgs = {};
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--source') args.source = argv[++i];
    else if (argv[i] === '--editor') {
      const v = argv[++i];
      if (v !== 'gutenberg' && v !== 'elementor') {
        throw new Error(`--editor must be "gutenberg" or "elementor", got "${v}"`);
      }
      args.editor = v;
    }
  }
  return args;
}

function sqlEscape(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function emitDeletes(targets: { editor: Editor; sourceName: string }[]): string {
  const slugs = targets.map((t) => `'${pageSlug(t.editor, t.sourceName)}'`).join(', ');
  return [
    `DELETE FROM wp_postmeta WHERE post_id IN (SELECT ID FROM wp_posts WHERE post_name IN (${slugs}));`,
    `DELETE FROM wp_posts WHERE post_name IN (${slugs});`,
  ].join('\n');
}

function emitGutenberg(id: number, source: Source): string {
  const slug = pageSlug('gutenberg', source.source);
  const title = pageTitle('gutenberg', source.source);
  const content = buildGutenbergContent(source.url!);
  return `
-- ${source.source} (Gutenberg)
INSERT INTO wp_posts
  (ID, post_author, post_date, post_date_gmt,
   post_content, post_title, post_status, post_type,
   post_name, comment_status, ping_status,
   to_ping, pinged, post_content_filtered, post_excerpt, guid)
VALUES (
  ${id}, 1,
  '2024-01-01 00:00:00', '2024-01-01 00:00:00',
  '${sqlEscape(content)}',
  '${sqlEscape(title)}',
  'publish', 'page',
  '${slug}',
  'open', 'open',
  '', '', '', '',
  'http://localhost:8080/?page_id=${id}'
);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES
  (${id}, '_wp_page_template', 'default');
`;
}

function emitElementor(id: number, source: Source): string {
  const slug = pageSlug('elementor', source.source);
  const title = pageTitle('elementor', source.source);
  const elementorData = buildElementorData(source.url!);
  return `
-- ${source.source} (Elementor)
INSERT INTO wp_posts
  (ID, post_author, post_date, post_date_gmt,
   post_content, post_title, post_status, post_type,
   post_name, comment_status, ping_status,
   to_ping, pinged, post_content_filtered, post_excerpt, guid)
VALUES (
  ${id}, 1,
  '2024-01-01 00:00:00', '2024-01-01 00:00:00',
  '',
  '${sqlEscape(title)}',
  'publish', 'page',
  '${slug}',
  'open', 'open',
  '', '', '', '',
  'http://localhost:8080/?page_id=${id}'
);
INSERT INTO wp_postmeta (post_id, meta_key, meta_value) VALUES
  (${id}, '_wp_page_template',        'default'),
  (${id}, '_elementor_edit_mode',     'builder'),
  (${id}, '_elementor_template_type', 'wp-page'),
  (${id}, '_elementor_version',       '${ELEMENTOR_VERSION}'),
  (${id}, '_elementor_data',          '${sqlEscape(elementorData)}');
`;
}

function main(): void {
  const args = parseArgs(process.argv.slice(2));

  const all = getSources().filter((s) => s.url);
  const filtered = args.source
    ? all.filter((s) => s.source.toLowerCase() === args.source!.toLowerCase())
    : all;

  if (args.source && filtered.length === 0) {
    process.stderr.write(
      `error: source "${args.source}" not found in sources.json (or its url is null)\n`,
    );
    process.exit(1);
  }

  const editors: Editor[] = args.editor
    ? [args.editor]
    : ['gutenberg', 'elementor'];

  const targets: { editor: Editor; sourceName: string }[] = [];
  for (const s of filtered) {
    for (const e of editors) targets.push({ editor: e, sourceName: s.source });
  }

  const out: string[] = [
    '-- ╔═══════════════════════════════════════════════════════════╗',
    '-- ║ AUTO-GENERATED by seed/index.ts — do not edit by hand.    ║',
    '-- ╚═══════════════════════════════════════════════════════════╝',
    emitDeletes(targets),
  ];

  let nextId = SEED_ID_START;
  for (const s of filtered) {
    if (editors.includes('gutenberg')) out.push(emitGutenberg(nextId++, s));
    if (editors.includes('elementor')) out.push(emitElementor(nextId++, s));
  }

  process.stdout.write(out.join('\n') + '\n');
  process.stderr.write(`✓ Generated ${targets.length} page(s) for ${filtered.length} source(s)\n`);
}

main();
